/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as CategoriesCategorySlugIndexRouteImport } from './routes/categories/$categorySlug/index'
import { Route as CategoriesCategorySlugSubcategoriesBoardIdIndexRouteImport } from './routes/categories/$categorySlug/subcategories/$boardId/index'
import { Route as CategoriesCategorySlugTopicsTopicSlugIndexRouteImport } from './routes/categories/$categorySlug/topics/$topicSlug/index'
import { Route as CategoriesCategorySlugSubcategoriesBoardIdTopicsTopicSlugIndexRouteImport } from './routes/categories/$categorySlug/subcategories/$boardId/topics/$topicSlug/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategorySlugIndexRoute =
  CategoriesCategorySlugIndexRouteImport.update({
    id: '/categories/$categorySlug/',
    path: '/categories/$categorySlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesCategorySlugSubcategoriesBoardIdIndexRoute =
  CategoriesCategorySlugSubcategoriesBoardIdIndexRouteImport.update({
    id: '/categories/$categorySlug/subcategories/$boardId/',
    path: '/categories/$categorySlug/subcategories/$boardId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesCategorySlugTopicsTopicSlugIndexRoute =
  CategoriesCategorySlugTopicsTopicSlugIndexRouteImport.update({
    id: '/categories/$categorySlug/topics/$topicSlug/',
    path: '/categories/$categorySlug/topics/$topicSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesCategorySlugSubcategoriesBoardIdTopicsTopicSlugIndexRoute =
  CategoriesCategorySlugSubcategoriesBoardIdTopicsTopicSlugIndexRouteImport.update(
    {
      id: '/categories/$categorySlug/subcategories/$boardId/topics/$topicSlug/',
      path: '/categories/$categorySlug/subcategories/$boardId/topics/$topicSlug/',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/categories/$categorySlug/': typeof CategoriesCategorySlugIndexRoute
  '/categories/$categorySlug/subcategories/$boardId/': typeof CategoriesCategorySlugSubcategoriesBoardIdIndexRoute
  '/categories/$categorySlug/topics/$topicSlug/': typeof CategoriesCategorySlugTopicsTopicSlugIndexRoute
  '/categories/$categorySlug/subcategories/$boardId/topics/$topicSlug/': typeof CategoriesCategorySlugSubcategoriesBoardIdTopicsTopicSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/categories/$categorySlug': typeof CategoriesCategorySlugIndexRoute
  '/categories/$categorySlug/subcategories/$boardId': typeof CategoriesCategorySlugSubcategoriesBoardIdIndexRoute
  '/categories/$categorySlug/topics/$topicSlug': typeof CategoriesCategorySlugTopicsTopicSlugIndexRoute
  '/categories/$categorySlug/subcategories/$boardId/topics/$topicSlug': typeof CategoriesCategorySlugSubcategoriesBoardIdTopicsTopicSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/categories/$categorySlug/': typeof CategoriesCategorySlugIndexRoute
  '/categories/$categorySlug/subcategories/$boardId/': typeof CategoriesCategorySlugSubcategoriesBoardIdIndexRoute
  '/categories/$categorySlug/topics/$topicSlug/': typeof CategoriesCategorySlugTopicsTopicSlugIndexRoute
  '/categories/$categorySlug/subcategories/$boardId/topics/$topicSlug/': typeof CategoriesCategorySlugSubcategoriesBoardIdTopicsTopicSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/categories/$categorySlug/'
    | '/categories/$categorySlug/subcategories/$boardId/'
    | '/categories/$categorySlug/topics/$topicSlug/'
    | '/categories/$categorySlug/subcategories/$boardId/topics/$topicSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/categories/$categorySlug'
    | '/categories/$categorySlug/subcategories/$boardId'
    | '/categories/$categorySlug/topics/$topicSlug'
    | '/categories/$categorySlug/subcategories/$boardId/topics/$topicSlug'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/categories/$categorySlug/'
    | '/categories/$categorySlug/subcategories/$boardId/'
    | '/categories/$categorySlug/topics/$topicSlug/'
    | '/categories/$categorySlug/subcategories/$boardId/topics/$topicSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  CategoriesCategorySlugIndexRoute: typeof CategoriesCategorySlugIndexRoute
  CategoriesCategorySlugSubcategoriesBoardIdIndexRoute: typeof CategoriesCategorySlugSubcategoriesBoardIdIndexRoute
  CategoriesCategorySlugTopicsTopicSlugIndexRoute: typeof CategoriesCategorySlugTopicsTopicSlugIndexRoute
  CategoriesCategorySlugSubcategoriesBoardIdTopicsTopicSlugIndexRoute: typeof CategoriesCategorySlugSubcategoriesBoardIdTopicsTopicSlugIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categorySlug/': {
      id: '/categories/$categorySlug/'
      path: '/categories/$categorySlug'
      fullPath: '/categories/$categorySlug/'
      preLoaderRoute: typeof CategoriesCategorySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categorySlug/subcategories/$boardId/': {
      id: '/categories/$categorySlug/subcategories/$boardId/'
      path: '/categories/$categorySlug/subcategories/$boardId'
      fullPath: '/categories/$categorySlug/subcategories/$boardId/'
      preLoaderRoute: typeof CategoriesCategorySlugSubcategoriesBoardIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categorySlug/topics/$topicSlug/': {
      id: '/categories/$categorySlug/topics/$topicSlug/'
      path: '/categories/$categorySlug/topics/$topicSlug'
      fullPath: '/categories/$categorySlug/topics/$topicSlug/'
      preLoaderRoute: typeof CategoriesCategorySlugTopicsTopicSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categorySlug/subcategories/$boardId/topics/$topicSlug/': {
      id: '/categories/$categorySlug/subcategories/$boardId/topics/$topicSlug/'
      path: '/categories/$categorySlug/subcategories/$boardId/topics/$topicSlug'
      fullPath: '/categories/$categorySlug/subcategories/$boardId/topics/$topicSlug/'
      preLoaderRoute: typeof CategoriesCategorySlugSubcategoriesBoardIdTopicsTopicSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  CategoriesCategorySlugIndexRoute: CategoriesCategorySlugIndexRoute,
  CategoriesCategorySlugSubcategoriesBoardIdIndexRoute:
    CategoriesCategorySlugSubcategoriesBoardIdIndexRoute,
  CategoriesCategorySlugTopicsTopicSlugIndexRoute:
    CategoriesCategorySlugTopicsTopicSlugIndexRoute,
  CategoriesCategorySlugSubcategoriesBoardIdTopicsTopicSlugIndexRoute:
    CategoriesCategorySlugSubcategoriesBoardIdTopicsTopicSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
