/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicTopicIdRouteImport } from './routes/topic.$topicId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'
import { Route as DemoStoreRouteImport } from './routes/demo.store'
import { Route as DemoFormRouteImport } from './routes/demo.form'
import { Route as DemoConvexRouteImport } from './routes/demo/convex'
import { Route as CategoryCategoryIdRouteImport } from './routes/category.$categoryId'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo.start.server-funcs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicTopicIdRoute = TopicTopicIdRouteImport.update({
  id: '/topic/$topicId',
  path: '/topic/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormRoute = DemoFormRouteImport.update({
  id: '/demo/form',
  path: '/demo/form',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexRoute = DemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryIdRoute = CategoryCategoryIdRouteImport.update({
  id: '/category/$categoryId',
  path: '/category/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/category/$categoryId'
    | '/demo/convex'
    | '/demo/form'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/topic/$topicId'
    | '/demo/start/server-funcs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/category/$categoryId'
    | '/demo/convex'
    | '/demo/form'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/topic/$topicId'
    | '/demo/start/server-funcs'
  id:
    | '__root__'
    | '/'
    | '/category/$categoryId'
    | '/demo/convex'
    | '/demo/form'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/topic/$topicId'
    | '/demo/start/server-funcs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryCategoryIdRoute: typeof CategoryCategoryIdRoute
  DemoConvexRoute: typeof DemoConvexRoute
  DemoFormRoute: typeof DemoFormRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  TopicTopicIdRoute: typeof TopicTopicIdRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$topicId': {
      id: '/topic/$topicId'
      path: '/topic/$topicId'
      fullPath: '/topic/$topicId'
      preLoaderRoute: typeof TopicTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form': {
      id: '/demo/form'
      path: '/demo/form'
      fullPath: '/demo/form'
      preLoaderRoute: typeof DemoFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categoryId': {
      id: '/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/category/$categoryId'
      preLoaderRoute: typeof CategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryCategoryIdRoute: CategoryCategoryIdRoute,
  DemoConvexRoute: DemoConvexRoute,
  DemoFormRoute: DemoFormRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  TopicTopicIdRoute: TopicTopicIdRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
